# Generated by Django 5.0 on 2024-01-04 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyseDesAchats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_evolution_achats', models.FloatField(max_length=30)),
                ('top_fournisseurs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AnalyseDesVentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('mois', models.IntegerField()),
                ('taux_evolution_ventes', models.FloatField(max_length=30)),
                ('taux_evolution_benefice', models.FloatField(max_length=30)),
                ('top_clients', models.TextField()),
                ('best_sellers', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('code_fournisseur', models.AutoField(primary_key=True, serialize=False)),
                ('nom_fournisseur', models.CharField(max_length=20)),
                ('prenom_fournisseur', models.CharField(max_length=30)),
                ('adresse_fournisseur', models.TextField()),
                ('telephone_fournisseur', models.CharField(max_length=20)),
                ('solde_fournisseur', models.FloatField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Magasin',
            fields=[
                ('code_magasin', models.AutoField(primary_key=True, serialize=False)),
                ('nom_magasin', models.CharField(max_length=50)),
                ('adresse_magasin', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Achat',
            fields=[
                ('numero_achat', models.AutoField(primary_key=True, serialize=False)),
                ('date_achat', models.DateField()),
                ('quantite_achetee', models.IntegerField()),
                ('montant_total_HT', models.FloatField(max_length=30)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre.produit')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasin.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='PaiementFournisseur',
            fields=[
                ('numero_paiement_fournisseur', models.AutoField(primary_key=True, serialize=False)),
                ('date_paiement_fournisseur', models.DateField()),
                ('montant_paiement_fournisseur', models.FloatField(max_length=30)),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasin.fournisseur')),
            ],
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('numero_transfert', models.AutoField(primary_key=True, serialize=False)),
                ('date_transfert', models.DateField()),
                ('quantite_transferee', models.IntegerField()),
                ('cout_transfert', models.FloatField(max_length=30)),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre.centre')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centre.produit')),
            ],
        ),
    ]
