# Generated by Django 5.0 on 2024-01-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='montant_recue',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='adresse_client',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employe',
            name='adresse_employe',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='magasin',
            name='adresse_magasin',
            field=models.CharField(max_length=100),
        ),
    ]
