# Generated by Django 5.0 on 2024-01-13 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0002_centre_client_produit_alter_transfert_centre_employe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centre',
            old_name='designation',
            new_name='designation_centre',
        ),
    ]
