# Generated by Django 5.0 on 2024-01-19 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0003_rename_designation_centre_designation_centre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achat',
            name='quantite_achetee',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
