# Generated by Django 5.0 on 2024-01-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0003_remove_vente_quantite_vendue_produitvente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='produit',
        ),
        migrations.AlterField(
            model_name='vente',
            name='montant_total_vente',
            field=models.FloatField(default=0, max_length=30),
        ),
    ]
