# Generated by Django 5.0 on 2024-01-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0004_alter_achat_quantite_achetee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='produit',
        ),
        migrations.AddField(
            model_name='achat',
            name='produits',
            field=models.ManyToManyField(related_name='produit_achat', to='magasin.produit'),
        ),
    ]
