# Generated by Django 5.0 on 2024-01-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0004_remove_vente_produit_alter_vente_montant_total_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='benefice_vente',
            field=models.FloatField(default=0),
        ),
    ]
