# Generated by Django 5.0 on 2024-01-19 17:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0005_remove_achat_produit_achat_produits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achat',
            name='quantite_achetee',
        ),
        migrations.CreateModel(
            name='ProduitAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prix_unitaire_HT', models.FloatField()),
                ('montant_total_HT', models.FloatField()),
                ('achat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasin.achat')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasin.produit')),
            ],
        ),
        migrations.AlterField(
            model_name='achat',
            name='produits',
            field=models.ManyToManyField(related_name='achats', to='magasin.produitachat'),
        ),
    ]
