# Generated by Django 5.0 on 2024-01-23 20:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0006_stockcentre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfert',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='transfert',
            name='quantite_transferee',
        ),
        migrations.CreateModel(
            name='ProduitTransfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('montant_vente_prd', models.FloatField()),
                ('prix_vente_unite', models.FloatField()),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasin.produit')),
                ('transfert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magasin.transfert')),
            ],
        ),
    ]
