# Generated by Django 5.0 on 2024-01-19 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0006_remove_achat_quantite_achetee_produitachat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achat',
            old_name='produits',
            new_name='produits_achat',
        ),
        migrations.RenameField(
            model_name='produitachat',
            old_name='montant_total_HT',
            new_name='montant_total_achat',
        ),
        migrations.AlterField(
            model_name='achat',
            name='date_achat',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
