# Generated by Django 5.0 on 2024-01-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0007_rename_produits_achat_produits_achat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produitachat',
            old_name='montant_total_achat',
            new_name='montant_prd',
        ),
        migrations.RemoveField(
            model_name='achat',
            name='produits_achat',
        ),
        migrations.RemoveField(
            model_name='produitachat',
            name='prix_unitaire_HT',
        ),
        migrations.AlterField(
            model_name='achat',
            name='montant_total_HT',
            field=models.FloatField(),
        ),
    ]
