# Generated by Django 5.0 on 2024-01-23 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0007_remove_transfert_produit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produittransfert',
            name='montant_vente_prd',
        ),
        migrations.RemoveField(
            model_name='produittransfert',
            name='prix_vente_unite',
        ),
        migrations.AlterField(
            model_name='transfert',
            name='cout_transfert',
            field=models.FloatField(default=0, max_length=30),
        ),
    ]
