# Generated by Django 5.0 on 2024-01-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0008_rename_montant_total_achat_produitachat_montant_prd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achat',
            name='montant_paye',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='achat',
            name='montant_total_HT',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='adresse_fournisseur',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='solde_fournisseur',
            field=models.FloatField(default=0, max_length=30),
        ),
    ]
