# Generated by Django 5.0 on 2024-01-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centre', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centre',
            old_name='désignation',
            new_name='designation',
        ),
    ]
